/* This file was autogenerated by ctest; do not modify directly */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <simple.h>

static char const* __test_const_A_val = A;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
 char const** __test_const_A(void) {
    return &__test_const_A_val;
}

static char const* __test_const_B_val = C_B;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
 char const** __test_const_B(void) {
    return &__test_const_B_val;
}

 uint64_t __test_size_Byte(void) { return sizeof(uint8_t); }
 uint64_t __test_align_Byte(void) {
    typedef struct {
        unsigned char c;
        uint8_t v;
    } type;
    type t;
    size_t t_addr = (size_t)(unsigned char*)(&t);
    size_t v_addr = (size_t)(unsigned char*)(&t.v);
    return t_addr >= v_addr? t_addr - v_addr : v_addr - t_addr;
}
 uint32_t __test_signed_Byte(void) {
    return (((uint8_t) -1) < 0);
}